### ISSUE TITLE
How can I use string.format to inject values into the query? 

### ISSUE THREAD

**Issue by otmezger** [prismagraphql/python-graphql-client#12]
Since the string starts with {}, this will be interpreted as a key in python's `String.format` function. What is the best way to programatically include values into the query?

**Comment by ssshah86** [comment]
Sorry, I don't fully understand your question. 

Are you talking about `headers[self.headername] = '{}'.format(self.token)` or the `_send` function?

**Comment by ssshah86** [comment]
I think what you're looking for is https://stackoverflow.com/questions/5466451/how-can-i-print-literal-curly-brace-characters-in-python-string-and-also-use-fo

See: https://docs.python.org/3/library/string.html#formatstrings
