### ISSUE TITLE
Certificate error on python 3.7

### ISSUE THREAD

**Issue by Gabri3l** [prismagraphql/python-graphql-client#13]
Hi, thanks for this nice little library!

I ran into a weird issue when using python 3.7 where I would get a certificate error as follows:

    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

The reason why this is weird is because I ran the exact same snippet with python 2.7 and everything worked nicely! Any idea on what might cause this ? Thanks!

**Comment by ssshah86** [comment]
Can you give more info from the traceback?

I don't know what function you are calling

**Edit** 
Sorry, it has been a long day. You're calling `urllib.request.urlopen` obviously

I'll look into this soon

**Comment by ssshah86** [comment]
What is your dev environment? OSX?

From SO: ```Take a look at this post, it seems like for later versions of Python, certificates are not pre installed which seems to cause this error.```

See here: https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org

Please let me know if this works and I'll close. Thanks.

**Comment by Gabri3l** [comment]
No worries! I'll check it out and yes I'm on OSX and you might be right because I tried on a Windows machine and it worked fine. Let me confirm then we can close! Thanks again!

**Comment by Gabri3l** [comment]
Yup that was it! We can close up here, thanks a lot!

**Comment by SuperBruceJia** [comment]
`
import urllib.request
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
response = urllib.request.urlopen('https://www.python.org')
print(response.read().decode('utf-8'))
`

**Comment by SuperBruceJia** [comment]
[https://blog.csdn.net/qq_25403205/article/details/81258327](url)

**Comment by SuperBruceJia** [comment]
`
import urllib.request
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
response = urllib.request.urlopen('https://www.python.org')
print(response.read().decode('utf-8'))

`
