### ISSUE TITLE
0.2.2 is broken due to missing read me file

### ISSUE THREAD

**Issue by olorogunthedread** [prismagraphql/python-graphql-client#9]
`from setuptools import setup

with open('README.md', 'r') as fh:
    long_description = fh.read()

graphqlclient-0.2.2/
graphqlclient-0.2.2/PKG-INFO
graphqlclient-0.2.2/graphqlclient/
graphqlclient-0.2.2/graphqlclient/client.py
graphqlclient-0.2.2/graphqlclient/__init__.py
graphqlclient-0.2.2/setup.py
graphqlclient-0.2.2/setup.cfg
graphqlclient-0.2.2/graphqlclient.egg-info/
graphqlclient-0.2.2/graphqlclient.egg-info/PKG-INFO
graphqlclient-0.2.2/graphqlclient.egg-info/not-zip-safe
graphqlclient-0.2.2/graphqlclient.egg-info/SOURCES.txt
graphqlclient-0.2.2/graphqlclient.egg-info/requires.txt
graphqlclient-0.2.2/graphqlclient.egg-info/top_level.txt
graphqlclient-0.2.2/graphqlclient.egg-info/dependency_links.txt`

**Comment by olorogunthedread** [comment]
`Collecting graphqlclient
  Downloading https://files.pythonhosted.org/packages/da/f2/b7def3fc54965b178eeb9c7fb82209f135d135c672e610b8c432e0e28e7f/graphqlclient-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-p796oz97/graphqlclient/setup.py", line 3, in <module>
        with open('README.md', 'r') as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'`

**Comment by ssshah86** [comment]
Hi, thanks. sorry for this I will take care of it

**Comment by olorogunthedread** [comment]
Ok.  I thought it was a simple fix to just add a readme file.

**Comment by ssshah86** [comment]
there is a `README.md` file, it worked in 0.2.2, not sure why it's failing

**Comment by ssshah86** [comment]
needed to use python3 to build sdist, should work now see: https://pypi.org/project/graphqlclient/0.2.4/

**Comment by olorogunthedread** [comment]
Awesome thank you.
